Vagrant.require_version ">= 1.7.0"

Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox"

  def set_vbox(vb, config)
    vb.gui = false
    vb.memory = 2048
    vb.cpus = 2

    config.vm.box = "bento/centos-7.3"
  end

  (0..2).each do |id|
    mid = id + 1
    ip = "10.64.0.1#{mid}"
    config.vm.define "kube-node#{mid}" do |node|
      node.vm.hostname = "kube-node#{mid}"
      node.vm.network :private_network, ip: "#{ip}",  auto_config: true

      node.vm.provider :virtualbox do |vb, override|
        vb.name = "kube-node#{mid}"
        set_vbox(vb, override)
      end
    end
  end
end
